# This is a Render Blueprint file.
# It defines the services and resources for your application.
# Render will automatically detect and use this file when you deploy.

services:
  # This defines our main web server
  - type: web
    name: group-connect # A name for your service
    runtime: node
    plan: free # Specifies the free instance type

    # The command to install dependencies, run on every deploy
    buildCommand: npm install

    # The command to start our server
    startCommand: node server.js

    # A health check path that Render uses to determine if your service is live
    healthCheckPath: /api/health

    # This section defines the persistent disk
    disks:
      - name: data-disk           # An internal name for the disk
        mountPath: /var/data     # The crucial path where the disk will be available inside your app
        sizeGB: 1                # 1GB is included in the free tier